name = "darkbr3w modpack"
author = "SpottyTheTurtle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efc39dc29b397188a017d581f90436e412dea541498c4eae1e18fc7a85f2ab89"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
