name = "darkbr3w modpack"
author = "SpottyTheTurtle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90aaf8d00691e5a19f0e4971788a3126a1cbb09f2725552cd9026341d171f4ea"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
