name = "darkbr3w modpack"
author = "SpottyTheTurtle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f27cdee7067f9670cf846d317d1fcbc482f1c021cdb27db0fb2a7e033293c278"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
